# Generated by Django 4.2.16 on 2024-10-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carSolutions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="celular",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="isfuncionario",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nacionalidade",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="rua",
        ),
        migrations.AddField(
            model_name="user",
            name="bairro",
            field=models.CharField(default="sem bairro", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="celular",
            field=models.CharField(default="00000000000", max_length=11),
        ),
        migrations.AddField(
            model_name="user",
            name="cep",
            field=models.CharField(default="00000000", max_length=8),
        ),
        migrations.AddField(
            model_name="user",
            name="cidade",
            field=models.CharField(default="sem cidade", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="complemento",
            field=models.CharField(default="sem complemento", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(default="00000000000", max_length=11),
        ),
        migrations.AddField(
            model_name="user",
            name="estado",
            field=models.CharField(default="XX", max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="sem nome", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outros")],
                default="O",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="isfuncionario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nacionalidade",
            field=models.CharField(default="Brasileiro", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="numero",
            field=models.CharField(default="000", max_length=5),
        ),
        migrations.AddField(
            model_name="user",
            name="rua",
            field=models.CharField(default="sem rua", max_length=100),
        ),
    ]
