# Generated by Django 4.2.16 on 2024-10-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carSolutions", "0002_remove_profile_bairro_remove_profile_celular_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bairro",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="celular",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="user",
            name="cep",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="user",
            name="cidade",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="complemento",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="user",
            name="estado",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="user",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outros")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nacionalidade",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="numero",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="rua",
            field=models.CharField(max_length=100),
        ),
    ]
