# Generated by Django 4.2.16 on 2024-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "carSolutions",
            "0003_alter_user_bairro_alter_user_celular_alter_user_cep_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isfuncionario",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
