# Generated by Django 4.2.16 on 2024-10-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carSolutions", "0004_alter_user_isfuncionario"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
