# Generated by Django 4.2.16 on 2024-10-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("ano", models.PositiveIntegerField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV"),
                            ("SEDAN", "Sedan"),
                            ("CAMINHONETES", "Caminhonetes"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_diaria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "tipo_de_produto",
                    models.CharField(
                        choices=[
                            ("Aluguel", "Somente para Aluguel"),
                            ("Venda", "Somente para Venda"),
                            ("Aluguel e Venda", "Para Aluguel e Venda"),
                        ],
                        default="Aluguel e Venda",
                        max_length=20,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="car_images/")),
                ("cambio", models.CharField(max_length=20)),
                ("combustivel", models.CharField(max_length=20)),
                ("cor", models.CharField(max_length=20)),
                ("placa", models.CharField(max_length=7)),
                ("is_disponivel", models.BooleanField(default=True)),
                ("data_publicado", models.DateTimeField(auto_now_add=True)),
                ("data_atualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_retirada", models.DateField()),
                ("hora_retirada", models.TimeField()),
                ("data_devolucao", models.DateField()),
                ("hora_devolucao", models.TimeField()),
                (
                    "local_retirada",
                    models.CharField(
                        choices=[
                            ("Congonhas", "Aeroporto de congonhas (CGH)"),
                            ("Guarulhos", "Aeroporto de Guarulhos (GRU)"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "local_devolucao",
                    models.CharField(
                        choices=[
                            ("Congonhas", "Aeroporto de congonhas (CGH)"),
                            ("Guarulhos", "Aeroporto de Guarulhos (GRU)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_reservations",
                        to="cars.car",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
