# Generated by Django 4.2.16 on 2024-11-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_breve", "Em Breve"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                default="em_breve",
                max_length=20,
            ),
        ),
    ]
