# Generated by Django 4.2.16 on 2024-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_carreservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreservation",
            name="preco_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
